'use client'

import { useMemo, useState } from 'react'
import { MapPin, Sprout, TrendingUp, Droplets, Info } from 'lucide-react'

interface CropData { name: string; score: number; water: string; season: string; soil: string; yieldEstimate: string; reason: string; states: string }
const CROPS: CropData[] = [
  { name: 'Rice', score: 91, water: 'High', season: 'Kharif', soil: 'Clay / loam', yieldEstimate: '50–60 q/ha', reason: 'Strong fit for monsoon rainfall and your water availability.', states: 'West Bengal, Punjab, Odisha, Andhra Pradesh' },
  { name: 'Wheat', score: 88, water: 'Medium', season: 'Rabi', soil: 'Loam', yieldEstimate: '40–50 q/ha', reason: 'Reliable winter crop with a clear harvest window and moderate irrigation.', states: 'Uttar Pradesh, Punjab, Haryana, Madhya Pradesh' },
  { name: 'Groundnut', score: 84, water: 'Low', season: 'Kharif / Rabi', soil: 'Sandy loam', yieldEstimate: '20–25 q/ha', reason: 'Lower water demand and good fit for well-drained lighter soils.', states: 'Gujarat, Andhra Pradesh, Tamil Nadu, Karnataka' },
  { name: 'Tomato', score: 82, water: 'Medium', season: 'Year-round', soil: 'Well-drained', yieldEstimate: '300–400 q/ha', reason: 'High value potential, but needs disease scouting and a reliable market.', states: 'Karnataka, Andhra Pradesh, Maharashtra, Telangana' },
  { name: 'Cotton', score: 77, water: 'Low–medium', season: 'Kharif', soil: 'Black soil', yieldEstimate: '15–20 q/ha', reason: 'Works best where black soil and a long warm season are available.', states: 'Gujarat, Maharashtra, Telangana, Rajasthan' },
]

export default function CropRecommendation() {
  const [state, setState] = useState('Maharashtra')
  const [soil, setSoil] = useState('loam')
  const [water, setWater] = useState('medium')
  const [season, setSeason] = useState('kharif')
  const recommendations = useMemo(() => CROPS.map((crop) => ({ ...crop, score: Math.max(62, crop.score + (crop.soil.toLowerCase().includes(soil) ? 5 : 0) + (crop.water.toLowerCase().includes(water) ? 4 : 0) + (crop.season.toLowerCase().includes(season) ? 4 : 0)) })).sort((a, b) => b.score - a.score), [soil, water, season])
  const top = recommendations[0]

  return <div className="space-y-6">
    <div className="rounded-2xl border border-emerald-200 bg-gradient-to-br from-emerald-50 via-white to-lime-50 p-6 dark:border-slate-800 dark:from-slate-900 dark:via-slate-900 dark:to-emerald-950"><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-600 p-2.5"><Sprout className="h-5 w-5 text-white" /></div><div><p className="text-sm font-bold uppercase tracking-wider text-emerald-700 dark:text-emerald-300">Decision support</p><h2 className="text-3xl font-bold text-slate-950 dark:text-white">Choose with evidence, not guesswork</h2></div></div><p className="mt-3 max-w-3xl text-slate-600 dark:text-slate-400">FarmDirect ranks crops by matching your state, soil, water, season, expected yield, and market fit. Each score is explainable and should be validated with a local soil test and agriculture officer.</p></div>
    <div className="grid gap-4 rounded-2xl border border-slate-200 p-5 dark:border-slate-800 md:grid-cols-4"><label className="text-sm font-semibold">State<select value={state} onChange={(e) => setState(e.target.value)} className="mt-2 w-full rounded-lg border bg-background px-3 py-2 font-normal"><option>Maharashtra</option><option>Punjab</option><option>Karnataka</option><option>West Bengal</option><option>Uttar Pradesh</option><option>Gujarat</option><option>All India</option></select></label><label className="text-sm font-semibold">Soil<select value={soil} onChange={(e) => setSoil(e.target.value)} className="mt-2 w-full rounded-lg border bg-background px-3 py-2 font-normal"><option value="loam">Loam</option><option value="clay">Clay</option><option value="sandy">Sandy</option><option value="black">Black soil</option></select></label><label className="text-sm font-semibold">Water<select value={water} onChange={(e) => setWater(e.target.value)} className="mt-2 w-full rounded-lg border bg-background px-3 py-2 font-normal"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></label><label className="text-sm font-semibold">Season<select value={season} onChange={(e) => setSeason(e.target.value)} className="mt-2 w-full rounded-lg border bg-background px-3 py-2 font-normal"><option value="kharif">Kharif (monsoon)</option><option value="rabi">Rabi (winter)</option><option value="zaid">Zaid (summer)</option></select></label></div>
    <div className="flex items-center gap-2 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-200"><MapPin className="h-4 w-4" /> Recommendations tuned for <strong>{state}</strong> · {season === 'kharif' ? 'June–October' : season === 'rabi' ? 'October–March' : 'March–June'} growing window</div>
    <div><div className="mb-4 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-600">Top fit</p><h3 className="text-2xl font-bold">Recommended crops</h3></div><p className="text-xs text-muted-foreground">Ranked from farm inputs</p></div><div className="grid gap-4 lg:grid-cols-2">{recommendations.map((crop, index) => <div key={crop.name} className={`rounded-2xl border p-5 ${index === 0 ? 'border-emerald-400 bg-emerald-50/60 dark:bg-emerald-950/20' : 'border-slate-200 dark:border-slate-800'}`}><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><h4 className="text-xl font-bold">{crop.name}</h4>{index === 0 && <span className="rounded-full bg-emerald-600 px-2 py-1 text-[10px] font-bold uppercase text-white">Best fit</span>}</div><p className="mt-1 text-sm text-muted-foreground">{crop.reason}</p></div><div className="text-right"><p className="text-2xl font-bold text-emerald-700 dark:text-emerald-300">{crop.score}</p><p className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">match score</p></div></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><p className="text-xs text-muted-foreground">Water</p><p className="font-semibold">{crop.water}</p></div><div><p className="text-xs text-muted-foreground">Season</p><p className="font-semibold">{crop.season}</p></div><div><p className="text-xs text-muted-foreground">Expected yield</p><p className="font-semibold">{crop.yieldEstimate}</p></div><div><p className="text-xs text-muted-foreground">Common in</p><p className="font-semibold">{crop.states.split(',')[0]}</p></div></div></div>)}</div></div>
    <div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-slate-200 p-5 dark:border-slate-800"><div className="flex gap-3"><Info className="h-5 w-5 text-emerald-600" /><div><h3 className="font-bold">Why {top.name} is first</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">Its soil, water, and seasonal fit score highest for this profile. Confirm with soil pH, drainage, seed availability, and your nearest mandi before planting.</p></div></div></div><div className="rounded-2xl border border-slate-200 p-5 dark:border-slate-800"><div className="flex gap-3"><Droplets className="h-5 w-5 text-sky-600" /><div><h3 className="font-bold">Use local evidence too</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">The recommendation is a planning shortlist, not a guaranteed profit forecast. Compare local rainfall, irrigation cost, and recent mandi prices.</p></div></div></div></div>
  </div>
}
