'use client'

import { useState } from 'react'
import { BadgeCheck, FlaskConical, Leaf, ShieldCheck, Sprout, Sun, Wind } from 'lucide-react'

const topics = [
  { id: 'pest', label: 'Pest & disease care', icon: ShieldCheck, title: 'Start with IPM, not a spray', body: 'Scout twice weekly, identify the pest and its life stage, then use the least disruptive control first. Treat only when the economic threshold is reached.', steps: ['Inspect the underside of leaves', 'Remove affected plant parts safely', 'Use traps, barriers, or beneficial insects', 'Follow the registered product label if treatment is needed'] },
  { id: 'fertilizer', label: 'Fertilizer plan', icon: FlaskConical, title: 'Feed the soil with evidence', body: 'Base nutrient decisions on a soil test, crop stage, and expected yield. Split nitrogen applications to reduce loss and protect water.', steps: ['Test pH, organic carbon, N, P, and K', 'Add compost only after checking maturity and salinity', 'Place nutrients near the root zone', 'Record product, dose, date, and field'] },
  { id: 'natural', label: 'Natural farming', icon: Leaf, title: 'Build a resilient living soil', body: 'Combine cover crops, crop rotation, mulch, compost, and habitat for beneficial insects. Natural inputs still need correct identification and dosage.', steps: ['Keep soil covered between crops', 'Rotate botanical families', 'Use well-made compost or farmyard manure', 'Monitor results instead of assuming every input works'] },
]

export default function FarmCareHub() {
  const [active, setActive] = useState('pest')
  const topic = topics.find((item) => item.id === active) ?? topics[0]
  const Icon = topic.icon
  return <div className="space-y-6">
    <section className="rounded-2xl border border-emerald-200 bg-emerald-950 p-6 text-emerald-50 md:p-8 dark:border-emerald-900"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-emerald-300">Field care library</p><h2 className="mt-2 text-3xl font-bold">Treat the cause, protect the soil.</h2><p className="mt-3 max-w-2xl leading-7 text-emerald-100/80">Practical guidance for safer crop protection, responsible fertilizer use, and natural farming. Always verify local registration and label instructions.</p></div><div className="rounded-2xl bg-emerald-800 p-4"><Sprout className="h-8 w-8 text-lime-300" /></div></div></section>
    <div className="grid gap-6 lg:grid-cols-[260px_1fr]"><aside className="space-y-2">{topics.map((item) => { const ItemIcon = item.icon; return <button key={item.id} onClick={() => setActive(item.id)} className={`flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-semibold transition ${active === item.id ? 'bg-emerald-700 text-white' : 'border border-emerald-100 bg-white text-slate-700 hover:bg-emerald-50 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300'}`}><ItemIcon className="h-5 w-5" />{item.label}</button> })}<div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-100"><BadgeCheck className="mb-2 h-5 w-5 text-amber-700" /><strong>Safety first.</strong> Never mix products, spray without PPE, or use a recommendation as a substitute for the product label.</div></aside>
      <section className="rounded-2xl border border-emerald-100 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-100 p-3 dark:bg-emerald-950"><Icon className="h-6 w-6 text-emerald-700 dark:text-emerald-300" /></div><div><p className="text-sm font-medium text-emerald-700 dark:text-emerald-300">Recommended workflow</p><h3 className="text-2xl font-bold text-slate-900 dark:text-white">{topic.title}</h3></div></div><p className="mt-5 max-w-2xl leading-7 text-slate-600 dark:text-slate-300">{topic.body}</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{topic.steps.map((step, index) => <div key={step} className="flex gap-3 rounded-xl bg-emerald-50 p-4 dark:bg-slate-800"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-emerald-700 text-sm font-bold text-white">{index + 1}</span><span className="text-sm leading-6 text-slate-700 dark:text-slate-200">{step}</span></div>)}</div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-slate-100 p-4 dark:border-slate-700"><Sun className="h-5 w-5 text-amber-500" /><p className="mt-2 text-xs font-semibold text-slate-500">Best practice</p><p className="mt-1 text-sm font-semibold text-slate-900 dark:text-white">Scout before deciding</p></div><div className="rounded-xl border border-slate-100 p-4 dark:border-slate-700"><Wind className="h-5 w-5 text-sky-500" /><p className="mt-2 text-xs font-semibold text-slate-500">Protect water</p><p className="mt-1 text-sm font-semibold text-slate-900 dark:text-white">Avoid runoff and drift</p></div><div className="rounded-xl border border-slate-100 p-4 dark:border-slate-700"><Leaf className="h-5 w-5 text-emerald-500" /><p className="mt-2 text-xs font-semibold text-slate-500">Keep records</p><p className="mt-1 text-sm font-semibold text-slate-900 dark:text-white">Learn each season</p></div></div></section></div>
  </div>
}
