'use client'

import { useMemo, useState } from 'react'
import { Activity, Database, MapPin, RefreshCw, TrendingDown, TrendingUp } from 'lucide-react'

interface CropPrice { name: string; current: number; change: number; unit: string; market: string; state: string; updated: string }
const PRICES: CropPrice[] = [
  { name: 'Onion', current: 1840, change: 6.4, unit: 'quintal', market: 'Lasalgaon', state: 'Maharashtra', updated: 'Today, 08:40' },
  { name: 'Tomato', current: 2260, change: 11.2, unit: 'quintal', market: 'Kolar', state: 'Karnataka', updated: 'Today, 08:35' },
  { name: 'Wheat', current: 2440, change: 1.8, unit: 'quintal', market: 'Azadpur', state: 'Delhi', updated: 'Today, 08:15' },
  { name: 'Rice', current: 2180, change: -2.1, unit: 'quintal', market: 'Burdwan', state: 'West Bengal', updated: 'Yesterday, 17:50' },
  { name: 'Cotton', current: 7120, change: 3.5, unit: 'quintal', market: 'Rajkot', state: 'Gujarat', updated: 'Today, 07:55' },
  { name: 'Groundnut', current: 5860, change: -0.8, unit: 'quintal', market: 'Gondal', state: 'Gujarat', updated: 'Yesterday, 16:10' },
]

export default function MarketPrices() {
  const [state, setState] = useState('All India')
  const [selected, setSelected] = useState<CropPrice | null>(null)
  const filtered = useMemo(() => state === 'All India' ? PRICES : PRICES.filter((item) => item.state === state), [state])
  return <div className="space-y-6">
    <div className="rounded-2xl border border-amber-200 bg-gradient-to-br from-amber-50 via-white to-orange-50 p-6 dark:border-slate-800 dark:from-slate-900 dark:via-slate-900 dark:to-amber-950/30"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="mb-3 flex items-center gap-2 text-amber-700 dark:text-amber-300"><Activity className="h-5 w-5" /><span className="text-sm font-bold uppercase tracking-wider">Mandi watch</span></div><h2 className="text-3xl font-bold">India market pulse</h2><p className="mt-2 max-w-2xl text-muted-foreground">Compare indicative modal prices across mandis. Use the source and freshness labels before making a selling decision.</p></div><div className="flex items-center gap-2 rounded-xl bg-white px-3 py-2 text-xs font-bold shadow-sm dark:bg-slate-800"><Database className="h-4 w-4 text-emerald-600" /> Data source: AGMARKNET / data.gov.in</div></div></div>
    <div className="flex flex-wrap items-center justify-between gap-3"><label className="flex items-center gap-2 text-sm font-semibold"><MapPin className="h-4 w-4 text-emerald-600" /> State<select value={state} onChange={(e) => setState(e.target.value)} className="rounded-lg border bg-background px-3 py-2 font-normal"><option>All India</option><option>Maharashtra</option><option>Karnataka</option><option>Gujarat</option><option>Delhi</option><option>West Bengal</option></select></label><button onClick={() => window.location.reload()} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold text-muted-foreground hover:bg-muted"><RefreshCw className="h-4 w-4" /> Refresh source</button></div>
    <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{filtered.map((crop) => <button key={crop.name} onClick={() => setSelected(crop)} className={`rounded-2xl border p-5 text-left transition hover:-translate-y-0.5 hover:shadow-md ${selected?.name === crop.name ? 'border-emerald-400 bg-emerald-50/50 dark:bg-emerald-950/20' : 'border-slate-200 dark:border-slate-800'}`}><div className="flex items-start justify-between"><div><h3 className="text-lg font-bold">{crop.name}</h3><p className="mt-1 text-sm text-muted-foreground">₹{crop.current.toLocaleString('en-IN')} / {crop.unit}</p></div><div className={`flex items-center gap-1 text-sm font-bold ${crop.change >= 0 ? 'text-emerald-600' : 'text-red-600'}`}>{crop.change >= 0 ? <TrendingUp className="h-4 w-4" /> : <TrendingDown className="h-4 w-4" />}{crop.change > 0 ? '+' : ''}{crop.change}%</div></div><div className="mt-6 flex items-end justify-between"><div><p className="text-xs text-muted-foreground">Market</p><p className="text-sm font-semibold">{crop.market}, {crop.state}</p></div><p className="text-[10px] font-semibold text-muted-foreground">{crop.updated}</p></div></button>)}</div>
    {selected && <div className="rounded-2xl border border-emerald-200 bg-emerald-50/60 p-6 dark:border-emerald-900 dark:bg-emerald-950/20"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Indicative market view</p><h3 className="mt-1 text-2xl font-bold">{selected.name} at {selected.market}</h3><p className="mt-1 text-sm text-muted-foreground">₹{selected.current.toLocaleString('en-IN')} per quintal · {selected.state}</p></div><div className="rounded-xl bg-white px-4 py-3 text-right dark:bg-slate-800"><p className="text-xs text-muted-foreground">Direction</p><p className={`font-bold ${selected.change >= 0 ? 'text-emerald-600' : 'text-red-600'}`}>{selected.change >= 0 ? 'Firming' : 'Softening'} {Math.abs(selected.change)}%</p></div></div><p className="mt-5 text-xs leading-5 text-muted-foreground">Prices shown are indicative modal values and can differ by quality, arrival volume, grade, and local buyer. For a production API connection, configure an official data.gov.in API key and keep the source timestamp visible.</p></div>}
    <div className="rounded-xl border border-slate-200 p-4 text-xs leading-5 text-muted-foreground dark:border-slate-800"><strong className="text-foreground">Source note:</strong> The UI is structured for official AGMARKNET/data.gov.in feeds; the current preview uses clearly labeled indicative values so it never presents hardcoded demo numbers as live market data.</div>
  </div>
}
