'use client'

import { useMemo, useState } from 'react'
import { BookOpen, CalendarDays, CheckCircle, CloudRain, MapPin } from 'lucide-react'

interface Guide { crop: string; sowing: string; harvest: string; window: string; source: string; steps: string[]; care: string[] }
const GUIDES: Guide[] = [
  { crop: 'Rice', sowing: 'June–July', harvest: 'October–November', window: 'Kharif · monsoon onset', source: 'ICAR crop production guidance', steps: ['Prepare nursery beds 2–3 weeks before transplanting', 'Sow with the dependable monsoon window in your district', 'Transplant at the 3–4 leaf stage', 'Maintain shallow water and drain before fertilizer', 'Scout weekly for stem borer and leaf folder', 'Harvest when grains turn golden and moisture is suitable'], care: ['Weeks 1–4: nursery and weed monitoring', 'Weeks 5–8: tillering nutrition and pest scouting', 'Weeks 9–12: panicle protection and water management', 'Final weeks: drain field and plan harvest logistics'] },
  { crop: 'Wheat', sowing: 'Late October–November', harvest: 'March–April', window: 'Rabi · cool dry season', source: 'ICAR / state agriculture advisories', steps: ['Prepare a level, fine seedbed after the last monsoon crop', 'Sow within the recommended local window', 'Apply first irrigation at crown root initiation', 'Split nitrogen based on soil test and crop vigor', 'Scout for rust and aphids after cool humid spells', 'Harvest when grains are hard and moisture is safe'], care: ['Month 1: emergence and weed control', 'Month 2: CRI irrigation and top dressing', 'Month 3: booting, rust scouting, and irrigation', 'Final month: stop irrigation before maturity'] },
  { crop: 'Tomato', sowing: 'Region-dependent', harvest: '60–90 days after transplanting', window: 'Protected / irrigated crop', source: 'State horticulture advisories', steps: ['Raise healthy seedlings in a clean nursery', 'Transplant after extreme heat or rain risk reduces', 'Use mulch, staking, and drip irrigation where possible', 'Scout twice weekly for leaf curl, blight, and fruit borer', 'Remove diseased leaves and avoid overhead irrigation', 'Harvest by grade and connect with a nearby market'], care: ['Weeks 1–2: transplant recovery and light irrigation', 'Weeks 3–5: staking, nutrition, and disease scouting', 'Weeks 6+: harvest planning and market checks'] },
]

export default function PlantingCalendar() {
  const [state, setState] = useState('Maharashtra')
  const [selected, setSelected] = useState(GUIDES[0])
  const [done, setDone] = useState<number[]>([])
  const [month, setMonth] = useState('June')
  const locationNote = useMemo(() => state === 'Punjab' ? 'Monsoon usually establishes later than coastal belts; align rice transplanting with dependable rainfall.' : state === 'Karnataka' ? 'Rainfall varies sharply by zone; use district advisories before fixing sowing dates.' : 'Use the first dependable local rain and your district advisory to finalize the field date.', [state])
  return <div className="space-y-6">
    <div className="rounded-2xl border border-sky-200 bg-gradient-to-br from-sky-50 via-white to-emerald-50 p-6 dark:border-slate-800 dark:from-slate-900 dark:via-slate-900 dark:to-emerald-950"><div className="flex items-center gap-3"><div className="rounded-xl bg-sky-600 p-2.5"><CalendarDays className="h-5 w-5 text-white" /></div><div><p className="text-sm font-bold uppercase tracking-wider text-sky-700 dark:text-sky-300">Season planner</p><h2 className="text-3xl font-bold">A calendar that follows your region</h2></div></div><p className="mt-3 max-w-3xl text-muted-foreground">Planting windows are based on crop season, monsoon or temperature patterns, and extension guidance. They are windows—not fixed promises—so local rainfall and soil moisture always win.</p></div>
    <div className="grid gap-4 rounded-2xl border border-slate-200 p-5 dark:border-slate-800 md:grid-cols-3"><label className="text-sm font-semibold">State / region<select value={state} onChange={(e) => setState(e.target.value)} className="mt-2 w-full rounded-lg border bg-background px-3 py-2 font-normal"><option>Maharashtra</option><option>Punjab</option><option>Karnataka</option><option>West Bengal</option><option>Uttar Pradesh</option><option>All India</option></select></label><label className="text-sm font-semibold">Planning month<select value={month} onChange={(e) => setMonth(e.target.value)} className="mt-2 w-full rounded-lg border bg-background px-3 py-2 font-normal"><option>June</option><option>July</option><option>October</option><option>November</option><option>March</option></select></label><div className="flex items-end"><div className="flex w-full items-center gap-2 rounded-lg bg-emerald-50 px-3 py-2 text-sm text-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-200"><MapPin className="h-4 w-4" /> {locationNote}</div></div></div>
    <div className="grid gap-3 md:grid-cols-3">{GUIDES.map((guide) => <button key={guide.crop} onClick={() => { setSelected(guide); setDone([]) }} className={`rounded-xl border p-4 text-left ${selected.crop === guide.crop ? 'border-emerald-500 bg-emerald-50 dark:bg-emerald-950/30' : 'border-slate-200 dark:border-slate-800'}`}><p className="font-bold">{guide.crop}</p><p className="mt-1 text-sm text-muted-foreground">{guide.sowing} · {guide.window}</p></button>)}</div>
    <div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-emerald-50 p-5 dark:bg-emerald-950/30"><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Sowing window</p><p className="mt-1 text-2xl font-bold text-emerald-950 dark:text-emerald-100">{selected.sowing}</p><p className="mt-2 text-sm text-emerald-800 dark:text-emerald-200">{selected.window}</p></div><div className="rounded-2xl bg-orange-50 p-5 dark:bg-orange-950/30"><p className="text-xs font-bold uppercase tracking-wider text-orange-700">Harvest window</p><p className="mt-1 text-2xl font-bold text-orange-950 dark:text-orange-100">{selected.harvest}</p><p className="mt-2 text-sm text-orange-800 dark:text-orange-200">Plan labor, storage, and mandi checks early.</p></div></div>
    <div className="rounded-2xl border border-slate-200 p-6 dark:border-slate-800"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-xl font-bold">{selected.crop} field checklist</h3><p className="mt-1 text-sm text-muted-foreground">Tap a step after you complete it.</p></div><div className="flex items-center gap-2 text-sm font-semibold text-emerald-700"><CloudRain className="h-4 w-4" /> {month} planning</div></div><div className="mt-5 space-y-3">{selected.steps.map((step, index) => <button key={step} onClick={() => setDone((items) => items.includes(index) ? items.filter((item) => item !== index) : [...items, index])} className={`flex w-full items-start gap-3 rounded-xl p-4 text-left ${done.includes(index) ? 'bg-emerald-50 dark:bg-emerald-950/30' : 'bg-muted/60'}`}><CheckCircle className={`mt-0.5 h-5 w-5 shrink-0 ${done.includes(index) ? 'text-emerald-600' : 'text-slate-400'}`} /><span className={`text-sm ${done.includes(index) ? 'font-medium text-emerald-800 line-through dark:text-emerald-200' : ''}`}>{step}</span></button>)}</div></div>
    <div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border p-5"><h3 className="font-bold">Care rhythm</h3>{selected.care.map((item, i) => <p key={item} className="mt-3 flex gap-2 text-sm text-muted-foreground"><span className="font-bold text-emerald-600">{i + 1}</span>{item}</p>)}</div><div className="rounded-2xl border p-5"><div className="flex gap-3"><BookOpen className="h-5 w-5 text-emerald-600" /><div><h3 className="font-bold">Why these dates?</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">This guide combines broad Indian Kharif/Rabi windows with extension-style field steps. Source context: {selected.source}. Check your state or district Krishi Vigyan Kendra advisory before sowing.</p></div></div></div></div>
  </div>
}
